var char = {
    //전열
    "리마": "Rima",
    "푸딩": "Miyako",
    "미야코": "Miyako",
    "쿠우카": "Kuuka",
    "쥰": "Jyun",
    //
    "카오리": "Kaori",
    //
    "페코린느": "Pekorinne",
    "루카": "Ruka",
    "노조미": "Nozomi",
    "무이미": "Muimi",
    "마코토": "Makoto",
    //
    //
    "아키노": "Akino",
    "마츠리": "Matsuri",
    //
    //
    "츠무기": "Tsumugi",
    "히요리": "Hiyori",
    "미소기": "Misogi",
    "아야네": "Ayane",
    "타마키": "Tamaki",
    "토모": "Tomo",
    "수마키": "SummerTamaki",
    "수영복타마키": "SummerTamaki",
    "타마키(여름)": "SummerTamaki",
    "에리코": "Eriko",
    "수페코": "SummerPekorinne",
    "수영복페코린느": "SummerPekorinne",
    "페코린느(여름)": "SummerPekorinne",
    "쿠루미": "Kurumi",
    "지타": "Djeeta",
    "레이": "Rei",
    "시즈루": "Shizuru",
    "크리스티나": "Christina",
    //
    //중열
    "미미": "Mimi",
    "시노부": "Shinobu",
    //
    "마히루": "Mahiru",
    "유카리": "Yukari",
    "모니카": "Monika",
    "니논": "Ninon",
    "미후유": "Mifuyu",
    "이리야": "Ilya",
    "사렌": "Saren",
    "안나": "Anna",
    "할노부": "HalloweenShinobu",
    "할로윈시노부": "HalloweenShinobu",
    "시노부(할로윈)": "HalloweenShinobu",
    "수후유": "SummerMifuyu",
    "수영복미후유": "SummerMifuyu",
    "미후유(여름)": "SummerMifuyu",
    "콧코로": "Kokkoro",
    "아유미": "Ayumi",
    "글레어": "Glare",
    "수코로": "SummerKokkoro",
    "수영복콧코로": "SummerKokkoro",
    "콧코로(여름)": "SummerKokkoro",
    "렘": "Rem",
    "람": "Ram",
    "린": "Rin",
    "미츠키": "Mitsuki",
    "아카리": "Akari",
    "요리": "Yori",
    "할푸딩": "HalloweenMiyako",
    "할로윈푸딩": "HalloweenMiyako",
    "할로윈미야코": "HalloweenMiyako",
    "미야코(할로윈)": "HalloweenMiyako",
    //후열
    "아리사": "Arisa",
    "앤": "Ann",
    "루": "Rou",
    "리노": "Rino",
    "스즈나": "Suzuna",
    //
    "시오리": "Shiori",
    "이오": "Io",
    //
    "스즈메": "Suzume",
    "에밀리아": "Emilia",
    "카스미": "Kasumi",
    "미사토": "Misato",
    "나나카": "Nanaka",
    //
    "캬루": "Kyaru",
    "하츠네": "Hatsune",
    "미사키": "Misaki",
    //
    "수즈메": "SummerSuzume",
    "수영복스즈메": "SummerSuzume",
    "스즈메(여름)": "SummerSuzume",
    "수캬루": "SummerKyaru",
    "수영복캬루": "SummerKyaru",
    "캬루(여름)": "SummerKyaru",
    "아오이": "Aoi",
    "치카": "Chika",
    "마호": "Maho",
    "유이": "Yui",
    "유키": "Yuki",
    "쿄우카": "Kyouka",
    "할사키": "HalloweenMisaki",
    "할로윈미사키": "HalloweenMisaki",
    "미사키(할로윈)": "HalloweenMisaki"
};
module.exports.char = char;
