Resources: 
  MatchTable: 
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: matchId
          AttributeType: S
        - 
          AttributeName: arenaType
          AttributeType: S
        - 
          AttributeName: attackPower
          AttributeType: "N"
        - 
          AttributeName: attackDeckId
          AttributeType: "N"
        - 
          AttributeName: defensePower
          AttributeType: "N"
        - 
          AttributeName: defenseDeckId
          AttributeType: "N"
        - 
          AttributeName: result
          AttributeType: S
        - 
          AttributeName: date
          AttributeType: S
        - 
          AttributeName: netUpvotes
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes: 
        - 
          IndexName: defenseVotes
          KeySchema: 
            - 
              AttributeName: defenseDeckId
              KeyType: HASH
            - 
              AttributeName: netUpvotes
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - 
          IndexName: attackVotes
          KeySchema: 
            - 
              AttributeName: attackDeckId
              KeyType: HASH
            - 
              AttributeName: netUpvotes
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - 
          IndexName: defenseDate
          KeySchema: 
            - 
              AttributeName: defenseDeckId
              KeyType: HASH
            - 
              AttributeName: date
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - 
          IndexName: attackDate
          KeySchema: 
            - 
              AttributeName: attackDeckId
              KeyType: HASH
            - 
              AttributeName: date
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      KeySchema: 
        - 
          AttributeName: matchId
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: match-table
    Type: "AWS::DynamoDB::Table"
