Resources: 
  VoterTable: 
    Properties: 
      AttributeDefinitions:
        - 
          AttributeName: matchId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - 
          AttributeName: matchId
          KeyType: HASH
      TableName: voter-table
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
              # github.io로 설정할 것
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
    Type: "AWS::DynamoDB::Table"
  MatchTable: 
    Properties: 
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
              # github.io로 설정할 것
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
      AttributeDefinitions: 
        - 
          AttributeName: matchId
          AttributeType: S
        - 
          AttributeName: attackDeckId
          AttributeType: "N"
        - 
          AttributeName: defenseDeckId
          AttributeType: "N"
        - 
          AttributeName: date
          AttributeType: S
        - 
          AttributeName: netUpvotes
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes: 
        - 
          IndexName: defenseVotes
          KeySchema: 
            - 
              AttributeName: defenseDeckId
              KeyType: HASH
            - 
              AttributeName: netUpvotes
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
        - 
          IndexName: attackVotes
          KeySchema: 
            - 
              AttributeName: attackDeckId
              KeyType: HASH
            - 
              AttributeName: netUpvotes
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
        - 
          IndexName: defenseDate
          KeySchema: 
            - 
              AttributeName: defenseDeckId
              KeyType: HASH
            - 
              AttributeName: date
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
        - 
          IndexName: attackDate
          KeySchema: 
            - 
              AttributeName: attackDeckId
              KeyType: HASH
            - 
              AttributeName: date
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
      KeySchema: 
        - 
          AttributeName: matchId
          KeyType: HASH
      TableName: match-table
    Type: "AWS::DynamoDB::Table"
